# Generated by Django 5.2.1 on 2025-08-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['rank']},
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the quiz is currently active'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
