# Generated by Django 5.2.1 on 2025-08-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes_title', models.CharField(blank=True, max_length=255)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
